server:
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://114.55.253.132:3306/myblog?userUnicode=true&characterEncoding=utf-8&userSSL=false
    username: hanshan
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.hanshan.mysqlgenerator.entity